"set softtabstop=2
"
call pathogen#infect()

set expandtab
set textwidth=80
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set number
set noerrorbells
set smarttab
set visualbell
set t_vb=
set laststatus=2
set ruler
:syntax on

" don't auto wrap lines
set wrap linebreak textwidth=0

"filetype plugin indent on

if has("gui_running")
    set lines=60 columns=80
endif

set background=dark
colorscheme solarized
set guifont=Inconsolata:h16

let g:indent_guides_enable_on_vim_startup = 1
