# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="vorce"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git osx python mvn)

source $ZSH/oh-my-zsh.sh

export GROOVY_HOME=~/bin/groovy-2.1.2
export GRADLE_HOME=~/.rvm/bin/gradle

# Customize to your needs...
export PATH=/Library/Frameworks/Python.framework/Versions/2.6/bin:~/.rvm/bin:~/.rvm/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/mysql/bin:~/Documents/src/elixir_v0.7.2/bin:/usr/local/git/bin:~/Documents/src/rabbitmq_server-3.0.2/sbin:~/bin:$GRADLE_HOME/bin:$GROOVY_HOME/bin:~/bin/storm-0.8.2/bin:/Users/joel.carlbark/work/hugo/scripts/bin:$PATH

alias pylint="pylint --reports=n --include-ids=y --disable=W0402 --const-rgx='[a-z_][a-z0-9_]{1,30}$'"
alias ls="ls -FGa"
alias grep="grep -n"
alias gvim="open"
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"

export CLICOLOR=1
export GIT_EDITOR=vim
export JAVA_HOME=$(/usr/libexec/java_home)
export PYTHONPATH=/lib/python2.7/site-packages/
export ANDROID_HOME=/Users/joel.carlbark/.rvm/opt/android-sdk
export M2_HOME=/Users/joel.carlbark/.rvm/opt/maven/libexec/
